 branches:
  only:
    - module-7

services:
  - docker

script:
  - echo "hello world"
  - docker build --target test --tag my-test-image . 
  - docker run my-test-image tests
  - docker run my-test-image e2e_tests

env:
  global:
    - TRELLO_TODOID=5fb51cfd98afad055cb08c82
    - TRELLO_DONEID=5fb51cfd98afad055cb08c84
    - TRELLO_BOARDID=5fb51cfd98afad055cb08c81
    - secure: "bpX0pgWyCtuKVrzS+o7SYZQyduwOHuzhZX+vErLlkxSYETJvwjGktB7AOKEBdaVEqWCplK+2C53xKjgIOX4pLCazeviicQIPLcoqPrKXhAOaxvnf8FPDwlEr1xjnjiqqyJK5jJpJ4zs8YGC3Nt93DyOsKOl7HsD4ZO+FoL3ry3dmzhFlNCxLCPqLAsBm20JlhbJBXW6fL04WOv51K4bAHcAZqLSzrXQ6LlcrtyHAAcMPYlpugIROp3EEQFQaSfXLGMcSZ1E0eU5vBUsKyo2c2Z77VZ6XgOLwuvZXaWCqWiDTNXKqDkYePCejeOZTbrHC4oeGfYdJfr4BC8o5+J20AZLTSY0/VhQ2GQrnLDoZODJrvZxjRbdgKvx+ShraISmGUiGF9ofQloWEVldnEJV5XlueSWk2B1hsR6GiZZmm+nakDr9fL0NXjyfoUqtlEwmi+h8uOtJjXf2TBJYp9Efl0kHT1wwC9TGodpWu5eUN6pS/vZxYxJMGQ5SnsZpcLU5T9IUam9f6g0oD5V8sUCFEUr2MiIAS903rZeMsO+P4GaCIyy3bbtW5O1AX1Jawpg8epZuUz4yUX9R3G67Jj3OmX/IO0SWvjtlA3vuP3Zxf9/wVGAclB/qL4nzhA4GJPnLjaMCmM3DfTtrQuY33KcCRM8caW3kfu7Rgt9M2Za82oKk="
    - secure: "Jp8ND4KCzKHtidt+RAIxGRY9weTvokLXi+eNWQo9Z8E5ofkSTLGzrdsKqjVJnK+Sz4Aj1OPaWE81xFYD5Uenp6ADWEtkMdBAqh8BmevIPaRb0E8yp/KBlCtyGr6L5WcYrE8bVZT5wC9j1nMCbbTBs+ivwkjHRaBLqdhAKuIFX8NPKt0P5J2nW44P8b3ZcCM/3RL19E4roNxTxVfIrActr7rCcwzSRRnL8oiEqYmr8bDwWCHZeLJ6WSUOKkIM212bfElgydMcxi7QW9S3oGi/zIVSGW+ihXukC/XPxZ7CTkxp+dtPBEQ2p8QuF5d8eRZUWSmjBB5jrG+ShCXiapAO9UOk+GgIq/21ubdEhLxXmFMr4fypqm6Eqg3rGcABW+MPk79S5SwaE5TkOIZ9oOKfy008Yi3iJukImlGzQLO09/6y/ry+H5uxkIksom7g2uS5vGk6ipr83glTLBA5cShuSN9fnh8jOh5aP1MJL8RuiwAwTARpHL83BThrD81KLADwi/2WcpRVMLE9XZ+BS4+Ji+XzoE7YO70jGldbNsFjYelEfzAbe0PlTsfirIk1I4QankcMm7LpsPZ07wXJ6ARSdLn1oz/gwVcE/8fCAHfugtS/kxK6BRjlpKPQezPjzQBCtXQO6TnJMATONmjgrLAGXH6M0nGxVSxaZ9q4hYlayNY="