services:
  - docker

branches:
  only:
    - master
    - module-8

script:
  - docker build --target test --tag my-test-image . 
  - docker run my-test-image tests
  - docker run --env SECRET_KEY --env TRELLO_TODOID --env TRELLO_DONEID --env TRELLO_BOARDID --env TRELLO_KEY --env TRELLO_TOKEN my-test-image test_e2e
before_deploy:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker build --target production --tag aj1993/my-image-prod:latest .
  - docker push aj1993/my-image-prod:latest
deploy:
  provider: script
  script: docker pull aj1993/my-image-prod:latest &&  docker tag aj1993/my-image-prod:latest registry.heroku.com/aptem-trello-app/web && docker push registry.heroku.com/aptem-trello-app/web




env:
  global:
    - SECRET_KEY=secret-key
    - secure: "wV+sfKT3Nsz2ll3GKf8SDwrbwTHvgTbz/9OHcQalaxW6tOS2LdX1GcHifTlK1JgNnEcORkvjk9asjcw3B1H9NbSZdw0+8pQn5//she0bALHIYDCYcZuRHqwjHtw3Y41YBbFE/8God/e6U/IwYy5Hrlt/SZavCmK/aw8ivfwehiZAe8oPhDq6KnJSErMgmdd2gS+xvClQuhK0p4isRel9XXIuARm1m8viAZtixQdbWH8lZ2pNEzQNdsLmJJ2WazjqkYz34g/sXYJcs8GIk5PlPj3HUWtRbX3DuikzmQdReuxkD7Q/3ONymNDb9xXd7jZGgCeMVGHd+A7Tu8B7eT9Vi7sUm9egs3NPTDD0tFoiKC8DR++WKMxuE8VaEMOnI/CfZaxOnqJOshCViCtOhxV6Il2KGtNjqjOZuf1IlUynD3yvI7V0trzyxwy728H8lCVSIfv7+dZ2Z5k3GX258ny6C00iD3zrqJ/OTv4AYPK3YEiyW/nRFhuDzrPI5JozQM8ibcvCrbYGf7qi6UWZxZ5X2BT1+KIk2ZVRUnSYJRbLeIsmy2MT2wiAcdx4itlrPwWmJiBRN4U8nhqjz/AUsWe+0cHzR1CAfsyjMeQOIEm70HAsU/dFaazHHCgaGFGy/2LyjH/de4SxjSvnF10cvH/7baOMD9aRSY4YeMIs3yNVLdE="
    - secure: "cJH8SmtvOLrVREmrpk7GLNHqlnBHFqdy1siyRYBa9aDMngRND8zakHiE6ybDUVdLehHlafPBo3QtkRddqj+Pyg4ldrc47g0x5riz/nd5WZ3wqpSdtUZdNOJdqNZVYevS8jmKQ0LuOPPC6Jy/PzwpNSqnP5ZJs5tucEyId2KaaqvX1hKKdo10Adr1nzXUhyPkvc57Uls+mHUMq0v5z24FAshXQlow2F+R7FgqFF4BMOMZFE3hCAOJpRCvPr7/VWs28bc6mEmFt+l333cipuH0wTFtZSsR0Ujk+71ksLID7e4YgHtq4xXS4yO+niorLgDvKhFvp5yNvUmYfN3kXD8tfQNGtLivDnqyJp6mI79+EQMS7yqHlTqRFYBqmhlATw1FIfdMi1Tsrv/XtRgXjKkLfjIqmk6Byjqv7hgqL+cirrdSpDwrTuMTRnZTqWBBoPFwaIbAc3q4YtoG4+sg5/sHQS04xHSAT3Jit1H6tqUBE3k/mPir08bJpVOzBvsvtXyGtr8ItxK2WenuTNjtjr+On/Y+FG7ljTYjQCU5ltyBER5A8tlryJfDDSu5DOGv2mNZf/8idPi6ZXQqZ/KeQyO3QXDkJyxEeJsH5rODNuqgSjDrPs3mqQpsden4JsxMf9OcWnzpOggJk28QIpTD2dsAma9WutviHBrbJZLUONlVZek="
    - TRELLO_TODOID=5fb51cfd98afad055cb08c82
    - TRELLO_DONEID=5fb51cfd98afad055cb08c84
    - TRELLO_BOARDID=5fb51cfd98afad055cb08c81
    - DOCKER_USERNAME=aj1993
    - secure: "sxh1iNdEEbyhmdPc265HjyNk+ZCffW5zIp3mBxaGEz2Ttwt7gbVKEC5A0DujBeh/dmUahOM1vsP1XPLu3IkTymB1a7EF+7mhyDQbfcunqcxaehYJFgOgK8NHf1SrgGGhlwd7JEk69XuTG9CZfmxqUC2eA+Ztinu9NcUt437THKZ9njX8Kq/1aMi7/5gqttiXZmzKlGzoBLitzUUr9H8AT95p3e82GldI3pVJjCvwLBN+r22zznIQ5z/o32kn9qts6uy+0EX8BUP0evW1px8VkKEAAYxV3/frzwJieJ3a1PF7a7KzG1397GYw60/V3HIdJ1XqiTBbxfFETY4TyC1PBVOQ6241m6Ueac69RrF4lCjECFUjnrDVdN1TWrD9yZrXl/MJAEKA0Gp6kFrhUJHwt2SKeiN6WgAkdFPQJvvVerZhPgy0jt4wUN9WKhM8fX1V+d7C+L7uTWibLRPxTMHFSiDFljyipd6D1Q5+RHode93ZfwplrdCKARjNLz8Lx0fnBHp3FpFESgEPKlkdocrnCF05AxcdypxJydqtzj5O+uZTw5IGiNtr/w6Ew47dHsD1mpyubfSpZNdkWtQdUxO75rgHiQwk6WwKcA8dpAlkOpk5De4HwxT6If4T9nhfJJnz2I3yy67MiKFrgG8DSDxbGV92ydkIOvP2N8EiODYBFVs="